sudo: false # faster builds

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: 'open-source'

language: java

jdk:
  - oraclejdk8

install:
  - 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'

script:
  - 'mvn test jacoco:report'
  - 'mvn sonar:sonar -Pcoverage'  

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
